# Generated by Django 2.2.4 on 2019-08-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.TextField()),
                ('year', models.IntegerField()),
                ('model', models.TextField()),
                ('gas_milage', models.IntegerField()),
            ],
        ),
    ]
